# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe25c06f31122e9d04b3b5350966703f4faf221760df502ba32e6d77ed2442b8897697728f47fbce3fca2479dbc1dd96892c200583fbaf1a5d03171756b9099d

test:
  secret_key_base: 0545761b933a5ebe412084e5ed5c0110cf620851c5b9e3bd8649c1eeaa2d2a2b2ee9a5497c184e23aec8532839779ec7be45759da450ca3f839ca6555eaf11f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
